routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PersonController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function(){
    return redirect()->route('home.index');
});

Route::resource('/home', HomeController::class);

Route::group(['middleware' => ['auth']], function(){
    Route::resource('contacts', PersonController::class);
});



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

app/Models/Contact.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Contact extends Model
{
    use HasFactory;

    public function person(): BelongsTo
    {
        return $this->belongsTo(Person::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use Illuminate\Http\Request;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $client = new Client();
        $response = $client->get('https://restcountries.com/v2/all');
        $countries = $response->getBody()->getContents();

        $countries = '123';

        return view('contacts.index', compact('countries');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function show(Contact $contact)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function edit(Contact $contact)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Contact $contact)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/home/create.blade.php
@extends('layouts.master')
@section('content')

    <div class="col-sm-12 content">
        <div class="bg-white">
            <div class="col-sm-12">
                <table class="table">
{{--                    {{ dd($countries[0]) }}--}}
                    <form action="{{ route('home.store') }}" method="POST">
                        @csrf
                        <h2>Adicionar Contato</h2>

                        <div class="form-group">
                            <th class="py-2 form-group">
                                <label for="name">Nome</label>
                                <input type="text" name="name" id="name" class="form-control" placeholder="Digite o nome">
                            </th>
                            <th class="py-2 form-group">
                                <label for="email">Email</label>
                                <input type="text" name="email" id="email" class="form-control" placeholder="Digite o email">
                            </th>
                            <th class="py-2 form-group">
                                <label for="single">Contatos</label><br />
                                <select id="single" class="js-states form-control">
                                    @foreach($countries as $contry)
                                        <option value="{{ $contry['name'] }} "> {{ $contry['name'] .' ('. $contry['callingCodes'][0] .')' }}</option>
                                    @endforeach
                                </select>
                            </th>
                            <th>
                                <img src="" alt="" style="width: 100px;height: 100px;">
                            </th>
                        </div>
                        <tr>
                            <td>
                                <a href="{{ route('home.index') }}" class="btn btn-outline-primary">Voltar</a>
                                <button href="" class="btn btn-outline-success">Salvar</button>
                            </td>
                        </tr>
                    </form>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/home/edit.blade.php
@extends('layouts.master')
@section('content')
    <div class="col-sm-12 content">
        <div class="bg-white">
            <div class="col-sm-12">
                <table class="table">
                    <form action="{{ route('home.update', $person->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <h2>Editar Contato</h2>

                        <div class="form-group">
                            <th class="py-2 form-group">
                                <label for="name">Nome</label>
                                <input type="text" name="name" id="name" value="{{ $person->name }}" class="form-control" placeholder="Digite o nome">
                            </th>
                            <th class="py-2 form-group">
                                <label for="email">Email</label>
                                <input type="text" name="email" id="email" value="{{ $person->email }}" class="form-control" placeholder="Digite o email">
                            </th>
{{--                            <th class="py-2 form-group">--}}
{{--                                <label for="name">Contato</label>--}}
{{--                                <input type="text" name="contato" id="contato" value="123123" class="form-control" placeholder="Digite o Contato">--}}
{{--                            </th>--}}
                            <th>
                                <img src="" alt="" style="width: 100px;height: 100px;">
                            </th>
                        </div>
                        <tr>
                            <td>
                                <a href="{{ route('home.index') }}" class="btn btn-outline-primary">Voltar</a>
                                <button type="submit" class="btn btn-outline-success">Editar</button>
                            </td>
                        </tr>
                    </form>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/home/show.blade.php
@extends('layouts.master')
@section('content')
    <div class="col-sm-12 content">
        <div class="bg-white">
            <div class="col-sm-12">
                <table class="table">
                    <tr>
                        <td>
                            <a href="{{ route('home.index') }}" class="btn btn-outline-primary">Voltar</a>
                            @auth
                                <a href="{{ route('home.create') }}" class="btn btn-outline-primary">Adicionar Contato</a>
                            @endauth
                        </td>
                    </tr>
                    <tr>
                        <th class="py-2">Nome</th>
                        <td>{{ $person->name }}</td>
                    </tr>
                    <tr>
                        <th class="py-2">Email</th>
                        <td>{{ $person->email }}</td>
                    </tr>
                    <tr>
                        <th class="py-2">Contato</th>
                        <td>123123</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
@endsection